### ISSUE TITLE
LocalVariableTable_attribute is missing in Method_Info attributes

### ISSUE THREAD

**Issue by thomasschlosser** [Delors/BAT#1]
Transformations of bytecode that contains local variable tables result in a BAT model instance that does not contain these information.

Simple example:
(Java Code):
    public void testMethod() {
    List<String> list = new ArrayList<String>();
    list.add(null);
    }

(Bytecode):
public void testMethod();
  Code:
   0:   new #17; //class java/util/ArrayList
   3:   dup
   4:   invokespecial   #19; //Method java/util/ArrayList."<init>":()V
   7:   astore_1
   8:   aload_1
   9:   aconst_null
   10:  invokeinterface #20,  2; //InterfaceMethod java/util/List.add:(Ljava/lang/Object;)Z
   15:  pop
   16:  return

  LineNumberTable: 
   line 8: 0
   line 9: 8
   line 10: 16

  LocalVariableTable: 
   Start  Length  Slot  Name   Signature
   0      17      0    this       Ltest/TestClass;
   8      9      1    list       Ljava/util/List;

Extracted (Method_Info) attributes:
Only the following Code_attribute is attached to the Method_Info object...

Code_attribute(maxStack=2, maxLocals=2,Array(NEW(ObjectType(className="java/util/ArrayList")), DUP, INVOKESPECIAL(ObjectType(className="java/util/ArrayList"),<init>,MethodDescriptor(parameterTypes=List(); returnType=VoidType)), ASTORE_1, ALOAD_1, ACONST_NULL, INVOKEINTERFACE(ObjectType(className="java/util/List"),add,MethodDescriptor(parameterTypes=List(ObjectType(className="java/lang/Object")); returnType=BooleanType)), POP, RETURN)WrappedArray(),WrappedArray())

**Comment by Delors** [comment]
Unfortunately, I cannot reproduce this error. However, I've included some demo code (in the demo folder) that can be used to easily debug the generated class file structure and it shows that the attribute is indeed there.

**Comment by thomasschlosser** [comment]
Hm...strange. Your demo shows exactly what you metioned above.
But when I use the "test.TestClass" that is contained in the "dependencyGraph"-branch's DepExtractorTestProject.zip file, it shows that there are no LocalVariableTables. When I use "javap -l" to look at this class file, I can see the LocalVariableTables (output is listed below).
Can you please replace line 39 of the demo code with the following line of code and have a look at the extracted class file structure once again?

> > val classFile = Java6Framework.ClassFile("test/classfiles/DepExtractorTestProject.zip", "test/TestClass.class")

Compiled from "TestClass.java"
public class test.TestClass extends java.lang.Object implements test.TestInterface{
public test.TestClass();
  LineNumberTable: 
   line 6: 0

  LocalVariableTable: 
   Start  Length  Slot  Name   Signature
   0      5      0    this       Ltest/TestClass;

public void testMethod();
  LineNumberTable: 
   line 8: 0
   line 9: 8
   line 10: 16

  LocalVariableTable: 
   Start  Length  Slot  Name   Signature
   0      17      0    this       Ltest/TestClass;
   8      9      1    list       Ljava/util/List;

public java.lang.String testMethod(java.lang.Integer, int);
  LineNumberTable: 
   line 13: 0
   line 14: 12
   line 16: 17

  LocalVariableTable: 
   Start  Length  Slot  Name   Signature
   0      22      0    this       Ltest/TestClass;
   0      22      1    i       Ljava/lang/Integer;
   0      22      2    j       I

}

**Comment by Delors** [comment]
I'm really sorry, but when I extract the mentioned class from the mentioned zip file and call " javap -s -l -private -verbose -classpath . test.TestClass" I get exactly the same information as BAT gives me. Are you sure that you are really refer to the right class when you call javap and that your classpath does not accidentally refer to another class with the same name?

**Comment by thomasschlosser** [comment]
Sorry, it was my fault. I accidentally used the wrong class file with the same name that was build with eclipse and not with the ant script. After setting the debug attribute of javac in the script to "true", I get the attributes as expected. Once again: Sorry for opening this issue and thanks for your help!
