### ISSUE TITLE
UseIDOfBaseTypeForArrayTypes: Array type int[] occurs in the resulting structure

### ISSUE THREAD

**Issue by thomasschlosser** [Delors/BAT#4]
After mixing the trait 'UseIDOfBaseTypeForArrayTypes' in, the array type 'int[]' still occurs in the resulting structure.
All the other calls of sourceElementID with array types were reduced to their corresponding base types.

**Comment by Delors** [comment]
Fixed the bug and added a test case to avoid that the bug will be reintroduced.

**Comment by thomasschlosser** [comment]
First of all, thanks for the fix.
The 'int[]' array type (and still all other array types) did no longer occur in the example that I used above.

This minute, I extracted the dependencies of hibernate and, curiously, the resulting structure contains array types.
And now not only to array types with primitive base types. Source elements of array types with object base types are also extracted and added to the structure.

This is the list of array types that occur in the resulting structure (Currently, I was not beeing able to extract any pattern that helps to identify the faulty code fragment):
boolean[]
byte[]
char[]
int[]
java.beans.PropertyDescriptor[]
java.io.Serializable[]
javax.persistence.Column[]
javax.persistence.ColumnResult[]
javax.persistence.EntityResult[]
javax.persistence.FieldResult[]
javax.persistence.JoinColumn[]
javax.persistence.UniqueConstraint[]
org.hibernate.annotations.JoinColumnOrFormula[]
org.hibernate.annotations.MetaValue[]
org.hibernate.annotations.ParamDef[]
org.hibernate.annotations.Parameter[]
org.hibernate.annotations.Tuplizer[]
org.hibernate.cfg.Ejb3Column[]
org.hibernate.cfg.Ejb3JoinColumn[]
org.hibernate.engine.ValueInclusion[]
org.hibernate.event.PreLoadEventListener[]
org.hibernate.hql.ast.ParameterTranslationsImpl$ParameterInfo[]
org.hibernate.hql.QueryTranslator[]
org.hibernate.loader.EntityAliases[]
org.hibernate.param.ParameterSpecification[][]
org.hibernate.property.Setter[]
org.hibernate.tuple.StandardProperty[]
org.hibernate.type.Type[]

**Comment by Delors** [comment]
fixed another bug related to the extraction of array types... hopefully it works now

**Comment by Delors** [comment]
(all bugs solved) 

Remark (if this bug seems to appear again): if the trait UseIDOf... is mixed in at the wrong place, it may happen that array types will be reported. (This is then a client error and not an error in BAT itself.)
